apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-drift-detection-service
  labels:
    app: {{ .Release.Name }}-drift-detection-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-drift-detection-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-drift-detection-service
    spec:
      containers:
        - name: drift-detection-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
