apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-drift-detection-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-drift-detection-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
